name: Tests

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

defaults:
  run:
    shell: bash

jobs:
  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11", "3.12", "3.13", "3.14" ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Run tests
        run: uv run --python ${{ matrix.python-version }} --group test pytest .

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  mypy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13", "3.14" ]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Validate type-hints with MyPy
        run: uv run --python ${{ matrix.python-version }} mypy src/

  pyright:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13", "3.14" ]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Validate type-hints with pyright
        run: uv run --python ${{ matrix.python-version }} pyright src/

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Check code formatting
        run: uv format --check
