name: Upload

on:
  workflow_run:
    workflows: [ "Tests" ]
    types:
      - completed
  push:
    branches: [ trunk ]

defaults:
  run:
    shell: bash

jobs:
  upload:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Build package
        run: uv build

      - name: Upload to PyPi
        run: uv publish --token ${{ secrets.PYPI_API_TOKEN }}
